### ISSUE TITLE
Property 'request' does not exist on type 'Response'.ts (2339)

### ISSUE THREAD

**Issue by mandarons** [chaijs/chai-http#294]
Versions:

chai: 4.3.4
chai-http: 4.3.0

Step to reproduce:

```
it('/favicon.ico should redirect to /', async () => {
        const response = await chai.request(service)
            .get('/favicon.ico');
        response.redirects[0].should.be.equal(response.request.url);
    });
```

Note: @types/chai-http is NOT installed.

**Comment by austince** [comment]
Would this be solved by https://github.com/chaijs/chai-http/pull/293 ?

**Comment by mandarons** [comment]
@austince it didn't. I made the one line change of -

```
 type Request = request.SuperAgentRequest;
```
in node-modules/chai-http/types/index.d.ts. It didn't fix the problem.

**Comment by austince** [comment]
I would think this is an issue with the superagent types then, if this is indeed a valid property.
